apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus/config-map.yaml
  - prometheus/prometheus-deployment.yaml
  - prometheus/prometheus-service.yaml
  - prometheus/alert-rules.yaml

  - grafana/config-map.yaml
  - grafana/grafana-deployment.yaml
  - grafana/grafana-service.yaml
