
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app: rewear-backend
  annotations:
    prometheus.io/scrape: "true"         
    prometheus.io/port: "80"              
    prometheus.io/path: "/metrics"        
  type: NodePort   # Ingress (ALB) will route to service; NodePort is okay because ALB controller targets pod IPs (target-type=ip)
  selector:
    app: rewear-backend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
