apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app: rewear-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
    app: rewear-backend
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.containerPort | default 5001 }}
