$ANSIBLE_VAULT;1.1;AES256
30393031613135666331326134386331353762353036326662353738363865313137613432373738
6232353030326330353366623661303736383336636461630a616637623161636366636631626232
39626331656630646132343366633335376334373930303264656230396434633731333166366363
3961373432613138320a613762663930346361346334306532633166643337333362373163666461
32633665356330353734373030323736356666643036363031303862636265323030373930393034
33383530343165626666303263653531616366313664373536646530363132656334663066323864
37656666323765636531393634333639373762616133663433336332623266343538616365386537
30656534666332613937626166623333313335333337323432383261353734626133636533643639
3966
