---
- name: Start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    key_name: "ansible-keypair"
    # vpc_subnet_id: subnet-5ca1ab1e
    aws_secret_key: "{{ec2_secret_key}}"
    aws_access_key: "{{ec2_access_key}}"
    instance_type: "{{ type }}"
    region: us-east-1
    security_group: default
    network:
      assign_public_ip: true
    image_id: "{{ item.image }}"
    tags:
      environment: "{{ item.name }}"
  
  loop: 
    - {image: "ami-0b6c6ebed2801a5cb", name: "manage-node-1" }
    - {image: "ami-0532be01f26a3de55", name: "manage-node-2"}
    - {image: "ami-0532be01f26a3de55", name: "manage-node-3"}
   
 