---
- name: Start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    # key_name: "network-keypair"
    # vpc_subnet_id: subnet-5ca1ab1e
    aws_secret_key: "{{ec2_secret_key}}"
    aws_access_key: "{{ec2_access_key}}"
    instance_type: "{{ type }}"
    security_group: default
    network:
      assign_public_ip: true
    image_id: ami-0532be01f26a3de55
   
