apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argpcd

spec:
  project: default
  source:  
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.46.8
    helm: 
      values: |
        serviceAccount:
          create: true
          name: fluent-bit
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::724772062958:role/rewear-eks-cluster-fluent-bit-irsa
        
        config:
         outputs: |
           [OUTPUT]
               Name kinesis_firehose
               Match *
               region us-east-1
               delivery_stream eks-logs-firehose

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:  

      prune: true
      selfHeal: true               

    
